### ISSUE TITLE
i18n not saving properly

### ISSUE THREAD

**Issue by Lirai** [codecombat/codecombat#1866]
Roughly 5% of my i18n contributions are not saving properly. They do not get the covered flags. Thus they show up again for me at the top, and according to Nick they are not filled in at all. The chat does show them as saved and my browser of course shows them to be filled in ... but they keep coming up as still not covered.

Eaxamples for this behaviour are:

Accepted a patch
Arcane Ally complete
Back to Back clean Code

all with the de-DE translation.

**Comment by nwinter** [comment]
Others have been reporting 403 Forbidden instead of 401 Unauthorized.

**Comment by sderickson** [comment]
401 Unauthorized is a fairly rarely used error on the server. I think the only way you'd get that is if, somehow, you stop being logged in, maybe by clearing cookies. I've made it so that these noty errors output more info, which hopefully will clarify that's the case.

I'd imagine the 403's are happening if two people try to translate the same document at the same time. It's a translation race condition. [These lines here](https://github.com/codecombat/codecombat/blob/master/app/views/i18n/I18NEditModelView.coffee#L139-L153) determine if the client should try to save a new version or submit a patch. First translators can just submit a new version, everyone else must patch. But if two clients think their both the first translators, the second submitter will get a 403, I believe.

This still doesn't explain the silent failures you're seeing. It's possible the errors happen without you realizing they do. I've made it so the button text says "submitting..." until something happens, so make sure you leave the page only after the button no longer says "submitting...", maybe that will help clarify things.

**Comment by Imperadeiro98** [comment]
This error appeared while trying to modify an existing achievement translation:

Validation failed for Patch: '[object Object]'.                         CocoModel.coffee:118
: Missing required property: commitMessage                      CocoModel.coffee:118
/target/collection : No enum match for: "achievement"        CocoModel.coffee:119
console.trace()                                                                     CocoModel.coffee:119
t.validate                                                                              CocoModel.coffee:119

**Comment by nwinter** [comment]
Do you know which achievement it was?

**Comment by Imperadeiro98** [comment]
First Level Translation

**Comment by nwinter** [comment]
@sderickson is there a reason why Achievement isn't in patchables? https://github.com/codecombat/codecombat/blob/master/app/schemas/models/patch.coffee#L3-L3

**Comment by nwinter** [comment]
Another user reports 403s on ThangTypes, like Leather Belt, but not on LevelComponents.

**Comment by bloodiris0312** [comment]
When Achievements are translated, the following error appears:
"Error saving First Level Translation: 422 Unprocessable Entity id should not be included."

**Comment by Martin005** [comment]
Will this ever be fixed?

**Comment by sderickson** [comment]
Okay I think this should fix the errors @Imperadeiro98 was seeing. If there are further problems saving after these changes, we'll reopen this.

**Comment by Imperadeiro98** [comment]
Will test when in production.

**Comment by nwinter** [comment]
@sderickson Some users are still seeing 403s when saving i18n to ThangTypes.

**Comment by nwinter** [comment]
Looks like it's good!
