### ISSUE TITLE
Python list comprehension creates array of undefineds

### ISSUE THREAD

**Issue by delve** [codecombat/codecombat#2113]
I'm trying to use a list comprehension to filter the list created by findEnemies().
```
    enemies = self.findEnemies()
    if len(enemies):
        notMunchkins = [x for x in enemies if x.type != "munchkin"]
        if len(notMunchkins) > 0:
            self.say(len(notMunchkins))
            self.say(notMunchkins[0].type)
```
This creates what appears to be a list of undefined objects. 
```self.say(len(notMunchkins))``` says "2"
```self.say(notMunchkins[0].type)``` fails with "Cannot read property 'type' of undefined"
If I try ```distanceTo(notMunchkins[0])``` it fails with "distance to target is null". 

Have I botched my list comprehension somewhere or is this not working?

**Comment by delve** [comment]
A workaround is, of course, doing it this way:
```
        notMunchkins = []
        for x in enemies:
            if x.type != "munchkin":
                notMunchkins.append(x)
        if len(notMunchkins) > 0:
            self.say(notMunchkins[0].type)
```
but I'd rather use the listcomp

**Comment by nemoyatpeace** [comment]
What if you did:
[x for x in enemies if not x.type is 'munchkin']

Seems like the comparisons for .type work best with is operator

**Comment by popey456963** [comment]
Tried @nemoyatpeace 's solution in the editor, it worked, so I'll assume this issue is fixed.  If it not, please reopen @delve

**Comment by nwinter** [comment]
Although the workaround with `is` works, it does seem like a bug that the `==` doesn't, probably in Filbert. That said, I was trying to reproduce this with `type` and `value` and couldn't, so perhaps the latest Aether fixes got it, since these all work:

```python
coins = [c for c in coins if c.type == "coin"]
coins = [c for c in coins if c.type is "coin"]
coins = [c for c in coins if c.type != "bitcoin"]
coins = [c for c in coins if not c.type is "bitcoin"]
coins = [c for c in coins if c.value == 3]
coins = [c for c in coins if c.value != 3]
coins = [c for c in coins if c.value is 3]
coins = [c for c in coins if not c.value is 3]
```

**Comment by delve** [comment]
Testing in Backwoods Brawl I'm still seeing this behavior. Here's some example code demonstrating different output from 4 ways to achieve the same result. Of the 4 options here only the function and the for loop seem to work as expected.
```
def findNonMunchkins(enemies):
    return [x for x in enemies if x.type != "munchkin"]

loop:
    enemies = self.findEnemies()
    if len(enemies):
        funcListComp = findNonMunchkins(enemies)
        listComp = [x for x in enemies if x.type != "munchkin"]
        listCompIs = [x for x in enemies if not x.type is "munchkin"]
        forNotMunchkins = []
        for x in enemies:
            if x.type != "munchkin":
                forNotMunchkins.append(x)
        self.say("Function found " + len(funcListComp) + " non-munchkins.")
        self.say("Listcomp inequality found " + len(listComp) + " non-munchkins.")
        self.say("Listcomp is found " + len(listCompIs) + " non-munchkins.")
        self.say("For loop found " + len(forNotMunchkins) + " non-munchkins.")
    else:
        self.say("BORING")
```

I find it fascinating that wrapping ```[x for x in enemies if x.type != "munchkin"]``` into a function mysteriously makes it perform as expected. In theory all 4 list variables should be essentially the same, unless my relatively novice understanding of Python is incorrect. Also of note both of the unwrapped forms of list comprehension I've used here return undefined length including the form @nemoyatpeace suggested. Wrapping the ```is``` form does make it work as well.

**Comment by popey456963** [comment]
I'll reopen this until we decide whether it is still an issue or not.

**Comment by delve** [comment]
Here's a video demonstration of my results for the code in https://github.com/codecombat/codecombat/issues/2113#issuecomment-77746946
https://www.youtube.com/watch?v=udhexXpJfRI

**Comment by Vlevo** [comment]
"if" then "[x for x in ...]" seems to be the problem. see [here][1] for a post with small example.

  [1]: http://discourse.codecombat.com/t/list-comprehension-in-python-bug-or-anything-i-dont-understand/3361

**Comment by goerlitz** [comment]
Hi,
this problem still persists and it is really annoying (I'm have been using if statements and list comprehensions quite a lot of in my code and I was always stupefied why it did not work as expected). Here is some minimal code for further illustration (which I used for kilthgard-brawl):

```python
loop:
    throwers = self.findByType("thrower", self.findEnemies())
    if throwers:
        nearest = self.findNearest(throwers)
        others = [t for t in throwers if not t is nearest]
        self.say(others + " - " + throwers)
```
shows `"[object Object] - Zara,Grel"`, whereas

```python
loop:
    throwers = self.findByType("thrower", self.findEnemies())
    while throwers:
        nearest = self.findNearest(throwers)
        others = [t for t in throwers if not t is nearest]
        self.say(others + " - " + throwers)
        throwers = self.findByType("thrower", self.findEnemies())
```
shows `"[Zara] - Zara,Grel"`.

I cannot even use `type(others)` to figure out what kind of object that is. Moreover, why is my list enclosed in square brackets and the one returned by the API not?

**Comment by nemoyatpeace** [comment]
Just hit this error again:

```
ave = sum([y.size for y in yaks])/len(yaks)
big = []
for y in yaks:
    if y.size > ave:
        big.append(y)
hero.say(hero.findNearest(big))
```

This gives an error on the line `for y in yaks:`

```
ave = 3
big = []
for y in yaks:
    if y.size > ave:
        big.append(y)
hero.say(hero.findNearest(big))
```

This works fine.  So apparently the list comprehension is breaking the `yaks` array.

**Comment by nwinter** [comment]
I think the remaining bug is just this one: https://github.com/codecombat/aether/issues/133 - Python list comprehensions give error when reusing comprehension variable name

Naming your local variable something else makes your code work. I'm going to close it in favor of that one.
