### ISSUE TITLE
User Profile Picture not aligning properly on the login screen.

### ISSUE THREAD

**Issue by divyanshu013** [codecombat/codecombat#2157]
I uploaded a picture which was of resolution 1280*720 pixels when I observed this:

![issue](https://cloud.githubusercontent.com/assets/6682655/5924482/2d8e0864-a682-11e4-936c-10e806d1e015.png)

**Comment by popey456963** [comment]
Wow, that's a weird error.  I can't seem to replicate it, what version of firefox are you using?

**Comment by divyanshu013** [comment]
I'm using Firefox 35.0 @popey456963.

**Comment by popey456963** [comment]
Huh, that's so strange
![](http://i.imgur.com/niw57ky.png) 
 Could it be the image itself?  What's the dimensions?

**Comment by divyanshu013** [comment]
The dimensions are 1280 * 720 pixels

**Comment by marinintim** [comment]
Same in Chrome.

Adding `max-width: 98px` to `.site-chrome #site-nav .dropdown .dropdown-menu .user-dropdown-header img` will trigger image to be round, but proportions will not be correct
![2015-02-01-140006_679x729_scrot](https://cloud.githubusercontent.com/assets/66025/5991855/ae4fed46-aa1a-11e4-8a74-48ed1f664379.png)

**Comment by nwinter** [comment]
Could turn it into a background image with background-size: cover. That would center it along the largest dimension.

**Comment by divyanshu013** [comment]
Oh yes, I'll work on it.

**Comment by nwinter** [comment]
Fixed in #2247.

**Comment by divyanshu013** [comment]
@nwinter I'm still facing this issue.

![issue dp](https://cloud.githubusercontent.com/assets/6682655/6097071/a9d8c318-afd4-11e4-8fd2-e9e7847fbca5.png)

**Comment by nwinter** [comment]
I haven't deployed it yet, but it is fixed in development.

![screenshot 2015-02-08 08 18 16](https://cloud.githubusercontent.com/assets/99704/6097244/19802e64-af6b-11e4-848a-e1fa5a076e2f.png)

**Comment by divyanshu013** [comment]
Great ! You put up my pic for yours :smile:
