### ISSUE TITLE
Scrollbars are never displayed in the main site

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3213]
It would be useful to have a vertical scrollbar in long pages such as the [Thang Editor](http://codecombat.com/editor/thang).

Other pages such as the profile page, settings page, multiplayer page, legal page, contribute page, home page and about page also never display a scrollbar, though its lack is admittedly less noticeable in pages that don't have much scrolling content.

**Comment by Imperadeiro98** [comment]
Fixed by 902c39f?

**Comment by UltCombo** [comment]
I would love to test it, but I'm not home atm and the [live server has been down for the last 24 hours](https://discourse.codecombat.com/t/its-a-bug-or-not/6719).

**Comment by UltCombo** [comment]
@Imperadeiro98 Was that commit deployed to production? I'm still not seeing any scrollbars in the main site.

However, I noticed this issue seems to be a dupe of #2711. Let's continue the discussion there.

**Comment by Imperadeiro98** [comment]
Yeah, in commit 1cb8ecf (maybe it is not in br and cn yet?).

**Comment by UltCombo** [comment]
I just tried `direct.codecombat.com` via an US VPN, the scrollbars are appearing correctly. :smile:
I guess #2711 can be closed as well now.

**Comment by UltCombo** [comment]
It seems a bit odd though. The deploy was made about a week ago and the changes did not propagate to the BR CDN yet (tested with cache disabled).
