### ISSUE TITLE
localhost: stuck on campaign screen

### ISSUE THREAD

**Issue by UltCombo** [codecombat/codecombat#3216]
I've already imported the latest db dump, pulled the master branch, ran `brunch build`, restarted the Node server (`npm start`), disabled browser cache, and my localhost is still stuck on this screen:

![](http://i.imgur.com/kgTKIZg.png)

I've tried with both `production` and `master` branches. The production branch has no errors in the console while the master branch tries to load a non-existent `javascripts/app/vendor/aether-.js` file, but that seems unrelated to the issue.

I can bypass this issue by entering a world URL directly (e.g. `http://localhost:3000/play/dungeon`), but I'm now wondering whether this is an issue with my setup or an actual issue.

**Comment by UltCombo** [comment]
The request for `/db/campaign/-/overworld` is returning an empty array on my localhost, which is odd seeing as my `campaigns` collection seems correctly filled.

**Comment by UltCombo** [comment]
Looks like the [campaign handler's `getOverworld` method filters campaigns by `{type: 'hero'}`](https://github.com/codecombat/codecombat/blob/ee6be55a9d28f6ef2fd8703de6839b690c51fe02/server/campaigns/campaign_handler.coffee#L60), and the latest db dump's campaigns do not have a `type` property.

So it seems the issue is caused by the latest db dump being outdated.

**Comment by UltCombo** [comment]
In case anyone else faces the same issue, here's a quick script you can run in the mongo shell to workaround the issue:

```js
use coco;
db.campaigns.update({ slug: { $in: ['dungeon', 'forest', 'desert', 'mountain', 'glacier'] } }, { $set: { type: 'hero' } }, { multi: 1 });
```

Still, that is just a quick hack, so I think the issue should be kept open until the db dump is updated.

**Comment by nwinter** [comment]
I think we fixed the database dump for now–part of it had gotten too big, so we had to take the portraits out again (which you can [fix like this](http://discourse.codecombat.com/t/broken-images-after-updating-source-db-in-vagrant/4716/9?u=nick)).

MongoDB 3.2 will let us do the large query, so when that's out, the whole thing will work again. Or maybe Rob already used that and the portraits are included; I don't have time to check. Does the latest dump work for you?

**Comment by UltCombo** [comment]
It is working now, thanks. :smile:

Looks like the thang portraits are okay as well.

I'm still having an issue with the `/db/level/(slug)` route returning 404 for several levels, but that seems unrelated to the dump. I'll open another issue after I spend some time trying to debug it.

**Comment by nwinter** [comment]
The public dump now only has a few levels in it so that the dump is smaller, hopefully a good enough set for testing purposes.

**Comment by UltCombo** [comment]
Oh I see. I checked the `levels` collection, it only has 8 levels indeed.
I understand CodeCombat's levels have rights reserved, so I guess it makes sense.
